# Dependencies
markdown:         kramdown
highlighter:      Rouge

# Permalinks
permalink:        pretty

# Setup
title:            Dheepak Govindaraj
tagline:          ''
description:      'Data Enthusiast and Software Developer'
url:              https://dheepakg.github.io/
baseurl:          /

author:
  name:           'Dheepak'
  url:            dheepakg.github.io
  email:          ''
  github:         'https://github.com/dheepakg'
  twitter:        'https://twitter.com/dheeepakg'
  linkedin:       'https://www.linkedin.com/in/dheepak-govindaraj-83a22623/'


# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/dheepakg/dheepakg.github.io

plugins:
  - jekyll-gist
  - redcarpet
  - jemoji
