# Dependencies
highlighter:      rouge

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jemoji

# Permalinks
permalink:              /blog/:categories/:title/
# permalink:            blog/:categories/:year/:month/:day/:title/

# Setup
title:            'Dheepak Govindaraj'
name:             'Dheepak Govindaraj'
#tagline:          ''
description:      'Data Enthusiast and software developer'
#url:              http://vakila.github.io/
baseurl:
# blogurl:          /blog/

# Assets
images:         '/images'
pdfs:           '/pdf'

author:
  name:           'Dheepak Govindaraj'
  url:            dheepakg.github.io
  email:          'anjanavakil@gmail.com'
  github:         'https://github.com/dheepakg'
  twitter:        'https://twitter.com/dheeepakg'
  googleplus:     ''
  linkedin:       'https://www.linkedin.com/in/dheepak-govindaraj-83a22623/'

paginate:  3
# paginate_path: '/TPW/page:num/'

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/dheepakg/dheepakg.github.io

# Collections
collections:
  - TIL
  - TPW

# defaults:
#   -
#     scope:
#       path: ""
#       type: "projects" # a collection in your site, in plural form
#     values:
#       layout: "default"
