baseurl = "https://dheepakg.github.io/"
# baseurl = ""
DefaultContentLanguage = "en"
title = "Dheepak's blog"
theme = "beautifulhugo"
# themesDir = "../.."
enableEmoji = true
publishDir = "docs"


metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
#  homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
# subtitle = "Build a beautiful and simple website in minutes"
subtitle = ""
mainSections = ["post", "posts"]
# logo = "img/favicon/android-chrome-192x192.png" # avatar-icon.png # Expecting square dimensions
favicon = "img/favicon/favicon.ico"
dateFormat = "January 2, 2006"
commit = false
rss = true
comments = true
readingTime = true
wordCount = true
useHLJS = true
socialShare = true
delayDisqus = true
showRelatedPosts = true

[Author]
name = "Dheepak"
# website = ""
# email = "youremail@domain.com"
# facebook = "username"
github = "dheepakg"
twitter = "dheeepakg"
telegram = "dheepak"


[[menu.main]]
identifier = "Cat-Tags"
name = "Grouping"
weight = 1

[[menu.main]]
parent = "Cat-Tags"
name = "Categories"
url = "/Categories"
weight = 1


[[menu.main]]
parent = "Cat-Tags"
name = "Tags"
url = "/tags"
weight = 2
